### ISSUE TITLE
Fontit selkeämmäksi

### ISSUE THREAD

**Issue by apoikola** [okffi/open-api-definition#1]
Sivun fontit ovat todella vaikeasti luettavissa ainakin omalla koneellani. Harmaa teksti ei oikein erotu valkoisesta pohjasta. Perustekstin väri kannattaisi vaihtaa mustaksi tai miettiä koko värivalikoima uusiksi.

**Comment by smoinen** [comment]
Samaa mieltä. Tekstin kontrastia voisi lisätä ja mahdollisesti fonttia suurentaa. Vaaleanharmaa teksti valkoisella taustalla ei ole paras luettavuuden kannalta.

**Comment by Mygee** [comment]
Ratkaistu.
