### ISSUE TITLE
Käyttöä rajaavien ehtojen salliminen? Minkälaisten?

### ISSUE THREAD

**Issue by kyyberi** [okffi/open-api-definition#10]
FB ryhmässä tuli kritiikkiä:

Määritelmä näyttää ihan kivalta. Toki tiukalta. Joka voi olla ihan hyvä asia. Mutta esimerkiksi Yle API ei tulene määritelmää täyttämään. Yle API tulee olemaan avoimesti dokumentoitu, mutta emme varmaan ihan ensimmäiseksi tule tarjoamaan automaattisia rekisteröitymisiä. Tulemme asettamaan rajapinnan käytölle joukon ehtoja (API-lisenssi), samoin kuin varmaankin myös sisällöllisiä rajoituksia.
Silti koen, että olen "avaamassa rajapintoja", vaikkei määritelmään asti yllettäisikään (tai oltaisi edes tavoittelemassa).

**Comment by apoikola** [comment]
Olisi loistavaa, jos YLE:n ja muiden vastaavien organisaatioiden kanssa voitaisiin jumppia määritelmää läpi käytännön tapausten kannalta, koska määritelmästä ei ole paljoa iloa, jos sitä ei käytetä.

**Comment by willebra** [comment]
Oon samaa mieltä: määritelmä kannattaa koestaa käytännössä ja tarvittaessa tehdä muutoksia. Siten määritelmä saadaan käyttökelpoiseksi ja tueksi organisaatioille. Muuten riskinä on, että määritelmästä tulee osa hälyä.

Jarkon poimiman kommentin osalta on vielä hankala sanoa, mitä pitäisi muuttaa ja onko kaikki Yle:n tarpeet sellaisia, että rajapinta on avoin. Mutta esimerkiksi API-lisenssille on tilausta useammassakin kohtaa. Tältä osin määritelmää voisi kehittää siihen suuntaan, että minkälaiset API-lisenssiehdot ovat avoimen rajapinnan määritelmän mukaisia ja minkälaiset ei. Hienoa, jos tuohon saisi jonkun CC-lisensioidun esimerkkilisenssin mukaan.

**Comment by pe3** [comment]
Komppaan @willebra:n kommenttia, että "_minkälaiset API-lisenssiehdot ovat avoimen rajapinnan määritelmän mukaisia ja minkälaiset ei_". Tuolla #11 issuessa asiaa sivutaan kuormituksen osalta. Minkähänlaisia muita kohtuullisia ehtoja avoimelle rajapinnalle voi asettaa? Voisiko tämän issuen omistaa (ja uudelleennimetä) siitä keskustelulle (ping @apoikola)? 

Voiko esimerkiksi jonkinlaista viranomaisstatusta edellyttävä rajapinta olla avoin? Vai voiko vain viranomaisrajapinnan kanssa identtinen testirajapinta olla avoin, eikä varsinainen tuotantorajapinta, jota asiaa pohdiskelen issuessa: #18

**Comment by Mygee** [comment]
Versiossa 1.1 on mainittu: "Rajapintapalvelun julkisissa käyttöehdoissa voidaan määritellä, millä edellytyksillä (esimerkiksi palvelunestohyökkäysten torjumiseksi) rajapinnan käyttöä voidaan rajoittaa erikoistapauksissa." -> Mahdollisuus rajoittaa

ja

"Mahdolliset rekisteröitymiset ovat automaattisia. Käyttäjälle voidaan esimerkiksi luoda automaattisesti api-avain (tilastollinen käytön seuranta ja alustava liikenteen priorisointi). Käyttöönottoa tulee tukea asiakaslähtöisesti niin, että käyttäjän ongelmatilanteista opitaan ja palautteeseen reagoidaan. Avoimen rajapinnan on toimittava luotettavasti."

Ja tarkoituksena on siis laatia erikseen rajapinnan SLA liitteeksi, jossa otetaan sitten paremmin kantaa näihin vielä.
