### ISSUE TITLE
Turhan toiston poistaminen tilaajan hallitsemaa rajapintaa koskevasta kohdasta

### ISSUE THREAD

**Issue by smoinen** [okffi/open-api-definition#12]
Määritelmän viimeisessä luvussa (kaksi viimeistä virkettä) on turhaa toistoa.

Alkuperäinen:
*Tilaajan hallitsema rajapinta tarkoittaa rajapintaa, jota järjestelmän tilaajalla on oikeus käyttää ja levittää haluamallaan tavalla. Tällöin tilaaja voi halutessaan avata rajapinnan järjestelmäntoimittajasta riippumatta, mutta mikäli näin ei tehdä kyse ei ole avoimesta rajapinnasta. Mikäli tilaaja ei avaa rajapintaa, ei rajapinta ole ulkopuolisille avoin, jolloin kyse ei ole yleisesti ottaen avoimesta rajapinnasta.*

Muutosehdotus:
*Tilaajan hallitsema rajapinta tarkoittaa rajapintaa, jota järjestelmän tilaajalla on oikeus käyttää ja levittää haluamallaan tavalla. Tällöin tilaaja voi halutessaan avata rajapinnan järjestelmäntoimittajasta riippumatta. Mikäli näin ei tehdä, ei rajapinta ole ulkopuolisille avoin, jolloin kyse ei ole yleisesti ottaen avoimesta rajapinnasta.*

**Comment by pe3** [comment]
@smoinen tää olis hyvä saada pull requestiksi. Onnistuisko, että forkkaat tän repon oman käyttäjätunnukses alle, luot siellä feature-branchin muutoksineen ja sitten pull requestin takas tänne päärepoon. Kaiken tän pitäs onnistua selaimessa. 

ping @apoikola

**Comment by Mygee** [comment]
Matin @smoinen kommentti on huomioitu versiossa 1.1.
