### ISSUE TITLE
Sosiaalinen media (iconit) ja logot kuntoon.

### ISSUE THREAD

**Issue by Mygee** [okffi/open-api-definition#15]
Tarvitaan logo avoimelle rajapinnalle.

**Comment by jjaone** [comment]
En näe mitään tarvetta tällaiselle varsinkaan kun Issue:ssa ei ole mitenkään perusteltu tätä tai logojen tai ikonien käyttöä. Tässä on kai kyse siis rajapintamäärityksestä, eikä mistään brändättävästä tuotteesta tai myytävästä palvelusta..

**Comment by apoikola** [comment]
Määrityksen jalkauttaminen on ihan keskeinen osa hommaa ja siinä varmasti myös some-kanavilla on oma roolinsa. Ei varmaankaan mikään high-priority juttu, mutta en nyt sulkisi kuitenkaan.

**Comment by pe3** [comment]
Mä en oikeen ymmärrä mitä @Mygee tarkoitat näillä: "sosiaalinen media (iconit)" ja "logot". Ja milloin ne olisivat kunnossa (eli siis definition of done)?

**Comment by d2s** [comment]
`gh-pages` branch sisältää `_config.yml` -tiedoston, jossa [määritetään](https://github.com/okffi/open-api-definition/blob/gh-pages/_config.yml#L88) käytössä olevalle teemalle kolmannen osapuolen verkkopalveluiden osoitteet. Niitä ei kuitenkaan ole vielä tällä hetkellä näkyvissä ulkoasussa.

Palveluiden linkit / kuvakkeet tulevat tällä hetkellä [`_includes/header.html`](https://github.com/okffi/open-api-definition/blob/gh-pages/_includes/header.html#L11) -tiedostossa määriteltyyn kohtaan.

Jostakin syystä `_config.yml` -tiedostossa oleva [`display-social-icons: true`](https://github.com/okffi/open-api-definition/blob/gh-pages/_config.yml#L40) -muuttuja ei toimi oikein, joten pitäisi selvittää mistä niiden näkymättömyys johtuu.

**Comment by pe3** [comment]
Tarkoittaako tää siis [FB-](https://developers.facebook.com/docs/plugins/share-button) ja [Twitter-](https://about.twitter.com/resources/buttons)sharebuttoneita. Musta ne on aika lameja. En usko, että meidän kohderyhmä tarvii niitä ja lisäks ne vielä träkkää ihmisten nettikäyttymistä. Multa saa tarvittaessa itetehdyt JavaScript-funktiot, jotka tekee jakamisen noita (ja träkkäämistä) ilman. Mutta en usko, että tarvitaan. Sen sijaan on tärkeää, että og-metadatat sun muut on kunnossa, että some-jakaminen näyttää hienolta.

**Comment by d2s** [comment]
Samaa mieltä siitä että jakonapit ovat usein aika turhia. Kyllä suurin osa ihmisistä osaa kopioida URL-osoitteen osoiteriviltä, jos todella tahtovat sivun jakaa eteenpäin.

**Comment by Mygee** [comment]
Ok. Suljen issuen.
