### ISSUE TITLE
Dumppi-haun edellyttäminen kaikelle avoimelle datalle?

### ISSUE THREAD

**Issue by Mygee** [okffi/open-api-definition#16]
Pitäiskö olla määritelmässä mukana?

**Comment by apoikola** [comment]
Saattaa sekoittua avoimen datan ja avoimen APIn määritelmä. APIhan voi olla toiminnallisuuksiiltaan suppea tai laaja, mutta silti avoin.

Se onkin tietty hyvä kysymys, että onko riskinä, että jengi tehtailisi tarkoituksella liian suppeita APIa ja jättäisi relevantteja toiminnallisuuksia kuten datadumpin pois?

Joka tapauksessa IMHO data dump ei ole must have kamaa.

**Comment by d2s** [comment]
Kaiken datan irroittaminen järjestelmästä ei ole edes avoimen rajapinnan tavoitteiden mukaista, koska useiden järjestelmien (sekä bisnesmallien) kannalta järkevämpää on käyttää rajapintaa kuin alkaa tarjota 'täydellistä' kopiota datan sisällöstä. Data exporttien ongelma on usein siinä että ne ovat usein käytännön tasolla lähempänä raportteja, sillä alkuperäisissä tietokanta-pohjaisissa järjestelmissä data on yleensä hajautettuna eri paikkoihin. Data export ei siis välttämättä sisällä sellaisenaan käyttökelpoista rakennetta datasetille, vaikka se (esimerkiksi) JSON-muotoisena olisikin koneellisesti käsiteltävissä.

**Comment by Mygee** [comment]
Joku oli kuulema valittanut tästä, joten nyt tämä on täällä käsiteltynä (ja dokumentoituna). Eli alkuperäinen kommentti tarkoitti, että rajapinnan takana oleva data olisi saatavissa ajatuksella "select *" -> eli kaikki rajapinnan tarjoama data.

**Comment by d2s** [comment]
Osa rajapinta-toteutuksista (kuten [GraphQL](https://github.com/facebook/graphql)) mahdollistavat isojenkin datamäärien exporttaamisen jos hakuparametrit ovat liian laajat. Keskeisin ongelma on kuitenkin se että tuollaisen salliminen aiheuttaa monessa tapauksessa huomattavia suorituskyky-ongelmia. Export-mahdollisuus kaikesta datasta kerralla voi olla hyvä ominaisuus, mutta sen vaatiminen ei edistä tavoitteita rajapintojen määrän lisäämisestä.

**Comment by jjaone** [comment]
Jos rajapinnan kautta saatavilla oleva data on jo avointa (kuten tämän issuen otsikosssa lukee), ei sitä tarvitse API:n kautta olla kokonaisuudessaan exportattuna tarjollaa. Erillinen linkki "koko daravarantoon" riittää tai se on tarjottu saataville samasta paikasta kuin muukin data ja siis rakenteisempana ja/tai elementteinä API:sta..

**Comment by Mygee** [comment]
Käsitelty ja dokumentoitu.
