### ISSUE TITLE
Yhteystietojen päivittäminen

### ISSUE THREAD

**Issue by apoikola** [okffi/open-api-definition#2]
Keneen ja minkä foorumin kautta pitäisi olla yhteydessä, jos on jotain kysyttävää?

**Comment by pe3** [comment]
Suljetaanko issue suoritettuna? Tehdään uus myöhemmin?

**Comment by jjaone** [comment]
Miten tämä on suoritettu?

**Comment by pe3** [comment]
Njoo. Rikkihän noi näköjään on:
- [GitHub-repon etusivulla](https://github.com/okffi/open-api-definition): 

> Keskustelua:
> 
> Määritelmän kehitysversio on kommentoitavissa osoitteessa http://okf.fi/avoin-rajapinta Keskusteluketju > Finnish Open Data Ecosystem -facebookryhmässä ja toinen keskusteluketju JulkICT-strategia linkedin-> ryhmässä sekä kolmas Kokonaisarkitehtuurin osaamisyhteisössä. Otso Kivekäs on myös blogannut aiheesta.

- [määritelmän webisivulla](http://okffi.github.io/open-api-definition/)

> Anna palautetta

joka vie vanhaan google dokkariin

**Comment by pe3** [comment]
Suostuuko kukaan määritelmän yhteyshenkilöksi, onko sille tarvetta, vai otetaanko kaikki yhteystiedot pois ja ohjeistetaan tekemään issueita, jos jotakin korjattavaa?

**Comment by aapris** [comment]
Mä äänestän issueita, koska silloin kuka tahansa voi reagoida kommentoimalla (keskustelemalla) issueen. Mutta silloinkin täytyy olla joku, joka vastaa siitä, että joku reagoi issueihin jonkin ajan sisällä.

**Comment by Mygee** [comment]
Periaatteessa minä olen yhteyshenkilö.

**Comment by apoikola** [comment]
Molempi parempi - issuen jättämiseen voi olla monilla iso kynnyt, Mika
yhteyshenkilönä voi poimia relevanttia palautetta sähköpostitse tai muuten
ja kanavoida sen issueiksi. Olennaista, että kaikki päätyy issueiksi.

On Tue, Dec 1, 2015 at 12:00 PM, Mika Honkanen <notifications@github.com>
wrote:

> Periaatteessa minä olen yhteyshenkilö.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okffi/open-api-definition/issues/2#issuecomment-160919619>
> .
>



-- 
+358 44 337 5439
about.me/apoikola
