### ISSUE TITLE
Rajapinnan "interface" ja "boundary" -merkityksien eriyttäminen?

### ISSUE THREAD

**Issue by Mygee** [okffi/open-api-definition#20]
Tässä pohjaksi vanha juttuni aiheesta: http://ollintuumailut.blogspot.fi/2014/07/avoin-rajapinta-sote-uudistuksen-itn-ja.html

**Comment by Mygee** [comment]
Jos ei mennä kokonaisarkkitehtuuriin, niin tämä taitaa olla tuon palautteen pihvi: "Saamani kommentin (8.7.2014) pohjalta on tärkeää erotella kaksi käsitettä "Interface" ja "boundary". Tietotekniikkassa rajapinta on yleensä 'interface', kun taas organisaatioiden puolella kyseessä on 'boundary'. Nämä ovat keskenään eri käsitteitä, vaikka niillä onkin yhteinen suomennos."

**Comment by d2s** [comment]
Selkeämmälle suomenkielisten termien määrittelylle on varmasti tarvetta.

Olisiko hyvä lisätä jonkinlainen _Glossary_ -listaus dokumentin loppuun?
(_A list of often difficult or specialized words with their definitions, often placed at the back of a book._)

**Comment by Mygee** [comment]
Voidaan tehdä liitteenä. Niitä on muutenkin tulossa 5-6 kappaletta.
