### ISSUE TITLE
Tukijajoukon laajentaminen

### ISSUE THREAD

**Issue by apoikola** [okffi/open-api-definition#3]
Nyt OKF, COSS ja API Suomi - ketä muita kannattaisi pyytää mukaan?

**Comment by pe3** [comment]
Suljetaanko issue suoritettuna? Tehdään uus myöhemmin?

**Comment by kyyberi** [comment]
+1 sulkemiselle. Tehdään seuraava issue sitten vaikka kampanjatyyliin niin on deadline millon kuka tahansa voi sen sulkea.

**Comment by jjaone** [comment]
Jos olisi jossain (dokumentissa) kootusti näkyvissä ketkä ovat tukijoukkoon liittyneet tai avoimen API:n määritelmän sitoutuneet, niin tämän issuen voisi hyvin sulkea (ja avata uusi kun tarvitaan lisää supporter-porukkaa).

**Comment by kyyberi** [comment]
Tuolla http://avoinrajapinta.fi/about/
