### ISSUE TITLE
Määritelmän tekstin automaattinen päivittäminen Jekyll:iin

### ISSUE THREAD

**Issue by apoikola** [okffi/open-api-definition#5]
Pitäisi olla niin, että originaalimateriaali tulisi suoraan reposta julkiselle puolelle. Nyt tein vain gh-pagesin manuaalisesti, koska en osannut.

**Comment by apoikola** [comment]
Täällä on ohjeistuksia, miten voisi toimia ehkä..
https://stackoverflow.com/questions/15214762/how-can-i-sync-documentation-with-github-pages

**Comment by pe3** [comment]
gh-pages-haara on niin roskainen, mm `_drafts`, että ei houkuta ratkaisemaan tarvetta. master-branchiin voisi tehdä scripts-kansion, johon sh-skriptin, joka tekis about @apoikola:n vinkkaaman, mutta skriptiin pitää koodata mihin paikkaan gh-pagesissa määritelmä laitetaan ja miten se uudelleennimetään version mukaan. Ton `_posts`-kansion vois nimetä ja konffata toisin, että se olis selkee paikka määritelmän eri versioille.

**Comment by pe3** [comment]
Ihmettelin tuolla [hyväksytyn pull-requestin lopussa](https://github.com/okffi/open-api-definition/pull/13) miltä sivusto ainakin mulle näyttää.

**Comment by pe3** [comment]
@Mygee kenellä pallo sivuston korjailusta on?

**Comment by d2s** [comment]
@pe3 GitHub Pages branch ei ole roskainen. `_drafts` -hakemisto on tuolla sen takia, jotta siitä voi nähdä teeman tukemat syntaksi-esimerkit. Jätin kyseiset tarkoituksella tuonne talteen (erilliseen hakemistoon) jotta ne olisivat vielä tallessa. Samat löytyvät tosin myös alkuperäisen [teeman GitHub-projektista](https://github.com/steinvc/holo-alfa/tree/master/_posts) joten se toimii myös vaihtoehtoisena sijaintina niiden löytämiseen (jos haluat siivota kyseisen `_drafts` alihakemiston pois tieltä).

Pallo sivuston korjaamisesta on sillä joka jaksaa tehdä #23 -issuen vastauksessa mainitun JavaScript-pätkän (URL-osoitteen sijainnin testaamiseen). Itselläni ei juuri nyt ole aikaa.

**Comment by d2s** [comment]
En näe mitään järkevää syytä sille miksi `_posts` -kansiota kannattaisi nimetä uudestaan. Kyseinen nimeämistapa on [Jekyll -sivugeneraattorin nimeämis-konventio](http://jekyllrb.com/docs/structure/), jonka muuttaminen rikkoisi rakenteen ymmärrettävyyden monelle potentiaaliselle contributorille.

**Comment by Mygee** [comment]
@pe3  Moi, olen tämän viikon Itävallassa duunissa. @d2s on tehnyt pohjan Jekyllillä, jota sitten hieman muokkasin tähän. Vapaaehtoispohjaltahan tätä tehdään. Tosiaan aika helposti Jekyll menee rikki, joten muokkausten kanssa kannattaa olla varovainen. Kunhan nyt saadaan edes jonkinlainen Open API -työryhmä kasaan, niin se on jo paljon. Saa toki tehdä ja osallistua. Otson ja Jogin kanssa sovittiin, että määritelmän sisältöä päivitetä "iteratiivisesti" vaan hyvin maltillisesti, eli max. kerran vuodessa. Katselen tätä enemmän taas viikonloppuna. Nyt täytyy lähteä nauttimaan Wienistä (ja huomenna aamulla konffasta) :)

**Comment by pe3** [comment]
Sori @d2s ei ollut tarkoitus loukata. Mm. [nää vuoristokuvat](https://github.com/okffi/open-api-definition/tree/gh-pages/img) sai mut ajattelemaan, että joku on asiaa enempää miettimättä jättäny kaikki boilerplatet repoon.

**Comment by pe3** [comment]
@Mygee @d2s mäkin voin vähän jotain Jekyll-hommaa tehä. Tein joskus [tämmösen testin](https://github.com/pe3/data-repo-test), missä käytin GitHubin sisäänrakennettua Jekyll:iä YAML-JSON renderinä ja "staattisena backendinä" JavaScriptille.

**Comment by d2s** [comment]
@pe3 No worries. :+1: 

Jos ehdit, pull requestit ylimääräisten kuvatiedostojen karsimiseen ovat toki tervetulleita.

**Comment by Mygee** [comment]
Aletaan järjestämään määritelmän ympärille 3-4 tapaamista vuodessa noin 3 kuukauden välein, missä asioista keskustellaan ja niitä kehitetään.
